dist: bionic

language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'

jobs:
  include:
    - install: composer install
      before_script: chmod +x ./Build/Scripts/runTests.sh
      script: ./Build/Scripts/runTests.sh
